repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: 'v0.5.6'
  hooks:
    # Run the formatter.
    - id: ruff-format
    # Run the linter.
    - id: ruff
      args: [--fix]
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: 'v1.11.1'
  hooks:
    - id: mypy
      additional_dependencies: ['polars==1.4.1', 'pytest==8.3.2']
      exclude: utils|tpch
- repo: https://github.com/codespell-project/codespell
  rev: 'v2.3.0'
  hooks:
    - id: codespell
      files: \.(py|rst|md)$
      args: [--ignore-words-list=ser]
      exclude: ^docs/api-completeness.md$
- repo: local
  hooks:
    - id: check-api-reference
      name: check-api-reference
      pass_filenames: false
      entry: python -m utils.check_api_reference
      language: python
      additional_dependencies: [polars]
    - id: imports-are-banned
      name: import are banned (use `get_pandas` instead of `import pandas`)
      entry: (?<!>>> )import (pandas|polars|modin|cudf|pyarrow|dask)
      language: pygrep
      files: ^narwhals/
      exclude: ^narwhals/dependencies\.py
- repo: https://github.com/kynan/nbstripout
  rev: 0.7.1
  hooks:
    - id: nbstripout
- repo: https://github.com/adamchainz/blacken-docs
  rev: "1.18.0"  # replace with latest tag on GitHub
  hooks:
  -   id: blacken-docs
      args: [--skip-errors]
      additional_dependencies:
      - black==22.12.0
